[package]
name = "shared_types_holon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]
name = "shared_types_holon"

[dependencies]
derive-new = { workspace = true }
hdi = { workspace = true }
hdk = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid ={ workspace = true}