[package]
name = "shared_types_holon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]
name = "shared_types_holon"

[dependencies]
derive-new = { workspace = true }
hdi = { workspace = true }
serde = { workspace = true }
core_types = { workspace = true }