[package]
name = "shared_types_holon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]
name = "shared_types_holon"

[dependencies]
hdi = { workspace = true }
hdk = { workspace = true }
derive-new = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

uuid = { version = "1.8", features = ["serde", "v4"] }