[package]
name = "type_names"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.5"
strum = "0.27"
strum_macros = "0.27"
tracing = "0.1"
[dependencies.integrity_core_types]
path = "../integrity_core_types"


[dependencies.base_types]
path = "../base_types"
