pub mod loader;
mod enum_descriptor;
mod schema;
mod holon_descriptor;
mod holon_space;
mod value_descriptor;
mod type_descriptor;
mod relationship_descriptor;
mod schema_helpers;
mod descriptor_types;
mod property_descriptor;
