[package]
name = "type_definers_zome"
version = "0.1.0"
edition = "2021"

[lib]
# WASM and non-WASM compatible
crate-type = ["cdylib", "rlib"]
name = "type_definers"

[dependencies]
# General Dependencies

# Holochain Dependencies

# MAP Dependencies
type_definers = { workspace = true }

