schema:
  type_name: CoreSchema
  described_by:
    $ref:
      type_name: SchemaType
      schema: CoreSchema
      space: https://space.map/schema
  properties:
    name: MAP Core Schema
    description: All core types used by the MAP system

type_files:
  - test_holon_types.yml
  - property_types.yml
  - relationship_types.yml
  - enum_types.yml
  - enum_variant_types.yml
  - string_types.yml
  - integer_types.yml
  - boolean_types.yml