mod holon_staging_behavior;
mod readable_holon;
mod space_manager_behavior;
pub mod writable_holon;

pub mod context_behavior;
pub mod holon_collection_api;
pub mod holon_operations_api;
pub mod holon_reference;
pub mod holon_service_api;
pub(crate) mod readable_impl;
pub mod smart_reference;
pub mod staged_reference;
pub mod transient_collection_behavior;
pub mod transient_holon_behavior;
pub mod transient_reference;
pub(crate) mod writable_impl;

pub use context_behavior::HolonsContextBehavior;
// pub use factory::init_context_from_session;
pub use holon_collection_api::HolonCollectionApi;
pub use holon_operations_api::*;
pub use holon_reference::HolonReference;
pub use holon_service_api::HolonServiceApi;
pub use holon_staging_behavior::HolonStagingBehavior;
pub use readable_holon::ReadableHolon;
pub use smart_reference::SmartReference;
pub use space_manager_behavior::HolonSpaceBehavior;
pub use staged_reference::StagedReference;
pub use transient_collection_behavior::TransientCollectionBehavior;
pub use transient_holon_behavior::TransientHolonBehavior;
pub use transient_reference::TransientReference;
pub use writable_holon::WritableHolon;
