[package]
name = "holons"
version = "0.0.1"
edition = "2021"

[lib]
# WASM and non-WASM compatible
crate-type = ["cdylib", "rlib"]
name = "holons"

[dependencies]
# General Dependencies
serde = { workspace = true }
serde_json = { workspace = true }

# Holochain Dependencies
hdk = { workspace = true }
holons_integrity = { workspace = true }


# MAP Dependencies
holons_core = { workspace = true }
holons_guest = { workspace = true }
shared_types_holon = { workspace = true }

[dev-dependencies]
async-std = { workspace = true }
futures = { workspace = true }
pretty_assertions = { workspace = true }
#rstest = { workspace = true }
