[package]
name = "holons"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "holons"

[dependencies]
# General Dependencies
serde = { workspace = true }
serde_json = { workspace = true }

# Holochain Dependencies
hdk = { workspace = true }

holons_integrity = { workspace = true }


# MAP Dependencies
holons_core = { workspace = true }
holons_guest = { workspace = true }
shared_types_holon = { workspace = true }


[dev-dependencies]
# General dev-dependencies (platform-agnostic)
async-std = { workspace = true }
futures = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }

# Target-specific dev dependencies for non-WASM builds
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
holochain = { version = "0.3", default-features = false, features = ["test_utils", "sqlite-encrypted"] }
tokio = { version = "1.35.1", features = ["full"] }