[package]
name = "core_schema"
version = "0.1.0"
edition = "2021"

[lib]
# WASM and non-WASM compatible
crate-type = ["cdylib", "rlib"]
name = "core_schema"

[dependencies]
# General Dependencies
Inflector = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

# Holochain Dependencies
hdi = { workspace = true }
hdk = { workspace = true }

# MAP Dependencies
holons_core = { workspace = true }
shared_types_holon = { workspace = true }
descriptors = { workspace = true }

[dev-dependencies]
