[package]
name = "core_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { version = "1", features = ["derive"] }
#derive-new = "0.7"
#thiserror = "2"

[dependencies.integrity_core_types]
path = "../integrity_core_types"

#[dependencies.base_types]
#path = "../base_types"

[dependencies.uuid]
version = "1"
features = ["serde"]