[package]
name = "core_types"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
uuid = { workspace = true}
base_types = { workspace = true }
hdi = { workspace = true }
integrity_core_types = { workspace = true }