[package]
name = "integrity_core_types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
derive-new = "0.7"
thiserror = "2"
[dependencies.base_types]
path = "../base_types"
