[package]
name = "integrity_core_types"
version = "0.1.0"
edition = "2024"

[dependencies]
base_types = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
hdi = { workspace = true }