[package]
name = "json_schema_validation"
version = "0.1.0"
edition = "2021"

[dependencies]
# General
serde_json = "1.0.140"
jsonschema = "0.30.0"

# MAP Dependencies
shared_validation = {workspace = true}
