[package]
name = "holons"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "holons"

[dependencies]
hdk = { workspace = true }
hdi = { workspace = true}
holochain_integrity_types = { workspace = true }

holons_integrity = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
thiserror = { workspace = true }

#shared_types_holon = {workspace = true}


shared_types_holon = {workspace = true}

[dev-dependencies]
holochain = {version = "0.1.5-beta-rc.0", default-features = false, features = ["test_utils"] }
tokio = { version = "1.3", features = ["full"] }
futures = { version = "0.3.1", default-features = false }
rstest = "0.18.1"
async-std = "1.1.12"