[package]
name = "holons"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "holons"

[dependencies]
hdk = { workspace = true }
hdi = { workspace = true}
holochain_integrity_types = { workspace = true }


holons_integrity = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
thiserror = { workspace = true }

shared_types_holon = {workspace = true}
