[package]
name = "holons_integrity"
version = "0.0.1"
edition = "2021"

[lib]
# WASM and non-WASM compatible
crate-type = ["cdylib", "rlib"]
name = "holons_integrity"

[dependencies]


serde = { workspace = true }

shared_validation = { workspace = true }

# Holochain dependencies
hdi = { workspace = true }
holochain_integrity_types = { workspace = true }
holons_guest_integrity = { workspace = true }
integrity_core_types = { workspace = true }