[package]
name = "holons_integrity"
version = "0.0.1"
edition = "2024"

[lib]
# WASM and non-WASM compatible
crate-type = ["cdylib", "rlib"]
name = "holons_integrity"

[dependencies]
hdi = { workspace = true }
holochain_integrity_types = { workspace = true }

serde = { workspace = true }

shared_validation = {workspace = true}
integrity_core_types = {workspace = true}