[workspace]

resolver = "2"

members = [
    # Coordinator Zomes
    "../../zomes/coordinator/holons",
    # Integrity Zome
    "../../zomes/integrity/holons_integrity",
    # Shared Types and Validation
    "../../crates/shared_validation",
    "../../crates/type_system/base_types",
    "../../crates/type_system/core_types",
    "../../crates/type_system/integrity_core_types",
    "../../crates/type_system/type_names",
    # Shared Core & Guest Libraries
    "../../crates/holons_core",
    "../../crates/holon_dance_builders",
    "../../crates/holons_guest",
    "../../crates/holons_guest_integrity",
    "../../crates/holons_prelude",
    "../../crates/holons_trust_channel",
]

# Local workspace dependencies
[workspace.dependencies.holons]
path = "../../zomes/coordinator/holons"

[workspace.dependencies.holons_integrity]
path = "../../zomes/integrity/holons_integrity"

[workspace.dependencies.shared_validation]
path = "../../crates/shared_validation"

[workspace.dependencies.base_types]
path = "../../crates/type_system/base_types"

[workspace.dependencies.core_types]
path = "../../crates/type_system/core_types"

[workspace.dependencies.integrity_core_types]
path = "../../crates/type_system/integrity_core_types"

[workspace.dependencies.json_schema_validation]
path = "../../crates/json_schema_validation"

#[workspace.dependencies.json_schema_validation_cli]
#path = "../../crates/json_schema_validation_cli"

[workspace.dependencies.type_names]
path = "../../crates/type_system/type_names"

[workspace.dependencies.holons_client]
path = "../../crates/holons_client"


[workspace.dependencies.holons_core]
path = "../../crates/holons_core"

[workspace.dependencies.holon_dance_builders]
path = "../../crates/holon_dance_builders"

[workspace.dependencies.holons_guest]
path = "../../crates/holons_guest"

[workspace.dependencies.holons_guest_integrity]
path = "../../crates/holons_guest_integrity"

[workspace.dependencies.holons_prelude]
path = "../../crates/holons_prelude"

[workspace.dependencies.holons_trust_channel]
path = "../../crates/holons_trust_channel"

[workspace.dependencies.holons_test]
path = "../../tests/sweetests"

[workspace.dependencies]
async-trait = "0.1.51"
convert_case = "0.5"
derive-new = "0.7"
futures = { version = "0.3.1", default-features = false }
hex = "0.4"
hdi = "0.6"
hdk = "0.5"
holochain_integrity_types = "0.5"
holochain_serialized_bytes = "*"          # You may want to pin this if instability ever becomes an issue
Inflector = "0.11"
pretty_assertions = "1.4.0"
quick_cache = { version = "0.6.14", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.109"
sha2 = "0.10.8"
strum = "0.27"
strum_macros = "0.27"
thiserror = "2"
tracing = "0.1"
uuid = { version = "1", features = ["serde"] }



[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
