// Generated by npm run build:node-visualizers; edit host/conductora/visualizer-src instead.

// host/conductora/visualizer-src/discovery-explorer.js
function explorerClass(tree) {
  return class DiscoveryExplorer extends HTMLElement {
    ready = Promise.resolve();
    setContext(context) {
      this.dispose();
      this.context = context;
      this.ready = this.render(context);
    }
    setSpatialBudget({ width, height }) {
      if (!(height > 0) || !(width > 0)) throw new Error("Discovery explorer requires a positive parent allocation.");
      this.style.cssText = `box-sizing:border-box;max-width:${width}px;max-height:${height}px;overflow:auto;`;
    }
    setVisualizerInformationHandler(handler, name) {
      this.information = handler;
      if (!this.v) {
        this.v = document.createElement("button");
        this.v.type = "button";
        this.v.textContent = "\u24E5";
        this.v.dataset.discoveryVisualizerInformation = "true";
        this.v.addEventListener("click", () => this.information?.(this.v));
      }
      this.v.title = name;
      this.v.setAttribute("aria-label", `Inspect ${name}`);
      this.prepend(this.v);
    }
    async render(context) {
      this.replaceChildren();
      const { evidence, state } = context.discoveryExplorer;
      const current = () => this.context === context && this.isConnected;
      const title = document.createElement("h3");
      title.textContent = "How these choices were identified";
      const rationale = document.createElement("p");
      rationale.textContent = evidence.rationale;
      const boundary = document.createElement("p");
      boundary.dataset.discoveryBoundary = "true";
      boundary.textContent = evidence.stopReason === "holon_type_boundary" ? `Discovery stopped at the permitted HolonType boundary: ${evidence.endpoint}.` : `Discovery examined the available lineage through ${evidence.endpoint}.`;
      this.append(title, rationale, boundary);
      if (evidence.requestContext) {
        const request = document.createElement("p");
        request.textContent = evidence.requestContext;
        this.append(request);
      }
      const ordering = document.createElement("p");
      ordering.textContent = "Rust visited these levels from specialized to general. Nearest-level discovery for automatic selection stops at the first eligible level. Interactive alternatives include the full permitted chain shown here.";
      this.append(ordering);
      if (state.notice) {
        const notice = document.createElement("p");
        notice.setAttribute("role", "status");
        notice.textContent = state.notice;
        this.append(notice);
      }
      const preview = document.createElement("div");
      preview.dataset.discoveryPreview = "true";
      const showPreview = async (candidate, select = true) => {
        if (select) state.selected = candidate.visualizer;
        state.preview = candidate.visualizer;
        preview.textContent = "Opening candidate information\u2026";
        try {
          await context.inspectVisualizerCandidate?.(candidate.visualizer, preview);
        } catch (error) {
          if (current()) preview.textContent = `Unable to inspect: ${error.message ?? error}`;
        }
      };
      const selectRow = (candidate, container) => {
        const row = document.createElement("div");
        row.dataset.discoveryCandidate = "true";
        row.style.cssText = "padding:8px;border-bottom:1px solid var(--dahn-slot-border-color);";
        const label = document.createElement("button");
        label.type = "button";
        label.textContent = `${candidate.label}${candidate.current ? " \xB7 Current" : ""}`;
        const selected = state.selected?.equals(candidate.visualizer) ?? false;
        label.setAttribute("aria-pressed", String(selected));
        label.addEventListener("click", () => {
          state.selected = candidate.visualizer;
          this.querySelectorAll("[data-discovery-candidate] button[aria-pressed]").forEach((button) => button.setAttribute("aria-pressed", "false"));
          label.setAttribute("aria-pressed", "true");
        });
        const explanation = document.createElement("p");
        explanation.dataset.discoveryAssessment = "true";
        explanation.textContent = candidate.assessment === "viable" ? "Rust identified this declaration as eligible for the captured slot and Theme." : `Unavailable in the captured discovery: ${candidate.assessment.replaceAll("_", " ")}.`;
        const inspect = document.createElement("button");
        inspect.type = "button";
        inspect.textContent = "Inspect";
        inspect.addEventListener("click", () => {
          if (current()) void showPreview(candidate);
        });
        const choose = document.createElement("button");
        choose.type = "button";
        choose.textContent = "Choose";
        choose.disabled = candidate.current || candidate.assessment !== "viable" || !context.chooseVisualizerCandidate;
        choose.addEventListener("click", async () => {
          if (!current() || this.pending) return;
          const controller = this.controller = new AbortController();
          this.pending = true;
          const cancel = document.createElement("button");
          cancel.type = "button";
          cancel.textContent = "Cancel choice";
          cancel.addEventListener("click", () => controller.abort());
          const status = document.createElement("p");
          status.setAttribute("role", "status");
          status.textContent = "Changing Visualizer\u2026";
          row.append(status, cancel);
          choose.disabled = true;
          try {
            await context.chooseVisualizerCandidate(candidate.visualizer, controller.signal);
          } catch (error) {
            if (current()) status.textContent = controller.signal.aborted ? "Choice cancelled." : `Unable to change Visualizer: ${error.message ?? error}`;
          } finally {
            this.pending = false;
            this.controller = void 0;
            cancel.remove();
            if (current()) choose.disabled = false;
          }
        });
        row.append(label, explanation, inspect, choose);
        container.append(row);
        if (selected && tree) container.open = true;
      };
      for (const level of evidence.levels) {
        const group = document.createElement(tree ? "details" : "section");
        const heading = document.createElement(tree ? "summary" : "h4");
        heading.textContent = level.label;
        group.dataset.discoveryLevel = "true";
        heading.tabIndex = 0;
        if (state.selected?.equals(level.descriptor)) group.open = true;
        heading.addEventListener("click", () => {
          state.selected = level.descriptor;
        });
        if (!tree) heading.addEventListener("keydown", (event) => {
          if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            state.selected = level.descriptor;
          }
        });
        group.append(heading);
        const declarations = evidence.candidates.filter((candidate) => candidate.declarations.some((descriptor) => descriptor.equals(level.descriptor)));
        for (const candidate of declarations) selectRow(candidate, group);
        if (!declarations.length) {
          const empty = document.createElement("p");
          empty.textContent = "No candidate declaration was found at this level.";
          group.append(empty);
        }
        this.append(group);
      }
      const undeclared = evidence.candidates.filter((candidate) => !candidate.declarations.length);
      if (undeclared.length) {
        const group = document.createElement("section");
        const heading = document.createElement("h4");
        heading.textContent = "Not declared in the captured chain";
        group.append(heading);
        for (const candidate of undeclared) selectRow(candidate, group);
        this.append(group);
      }
      if (!evidence.levels.length) {
        const empty = document.createElement("p");
        empty.textContent = "No descriptor levels were captured.";
        this.append(empty);
      }
      this.append(preview);
      const retained = evidence.candidates.find((candidate) => state.preview?.equals(candidate.visualizer));
      this.restorePreview = retained ? () => showPreview(retained, false) : void 0;
      if (this.isConnected) await this.restorePreview?.();
    }
    connectedCallback() {
      void this.restorePreview?.();
    }
    dispose() {
      this.controller?.abort();
      this.controller = void 0;
      this.pending = false;
      this.information = void 0;
      this.context = void 0;
      this.restorePreview = void 0;
    }
    disconnectedCallback() {
      this.dispose();
    }
  };
}

// host/conductora/visualizer-src/discovery-levels.js
var discovery_levels_default = explorerClass(false);
export {
  discovery_levels_default as default
};
