import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { defineCustomElementOnce } from './define-custom-element-once';
let callbacks: FrameRequestCallback[];
let observers: (() => void)[];
beforeEach(() => {
  callbacks = []; observers = [];
  vi.stubGlobal('requestAnimationFrame', (cb: FrameRequestCallback) => { callbacks.push(cb); return callbacks.length; });
  vi.stubGlobal('cancelAnimationFrame', vi.fn());
  vi.stubGlobal('ResizeObserver', class { constructor(cb: () => void) { observers.push(cb); } observe() {} disconnect() {} });
});
afterEach(() => { document.body.replaceChildren(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
const flush = () => callbacks.splice(0).forEach(cb => cb(0));
const measure = (element: Element, width: number, height = 30) => vi.spyOn(element, 'getBoundingClientRect').mockReturnValue({ width, height, left: 0, top: 0, bottom: height } as DOMRect);
async function artifact(name: string) {
  const source = await readFile(resolve(process.cwd(), `conductora/resources/dahn-visualizers/${name}.js`), 'utf8');
  const module = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
  return document.createElement(defineCustomElementOnce(`test-overflow-${name}`, module.default)) as HTMLElement & { setContext(context: unknown): void };
}
it.each(['actions', 'holon-inspector'])('keeps %s horizontal controls in one row and exposes only spillovers in the disclosure', async name => {
  const element = await artifact(name);
  const items = ['One', 'Two', 'Three'].map(label => ({ label, id: label }));
  element.setContext({ actions: items, nodeAffordances: { collections: items } });
  const row = element.querySelector<HTMLElement>('[data-overflow-row]')!;
  const more = row.querySelector<HTMLButtonElement>('[data-overflow-more]')!;
  const buttons = [...row.querySelectorAll<HTMLButtonElement>('button:disabled')];
  row.style.gap = '10px';
  let width = 280;
  Object.defineProperty(row, 'clientWidth', { get: () => width });
  buttons.forEach(button => measure(button, 80)); measure(more, 100);
  document.body.append(element); flush();
  expect(buttons.every(button => button.style.visibility === 'visible')).toBe(true);
  expect(more.inert).toBe(true);
  width = 200; observers.forEach(cb => cb()); flush();
  expect(buttons.map(button => button.style.visibility)).toEqual(['visible', 'hidden', 'hidden']);
  expect(row.style.flexWrap).toBe('nowrap');
  more.click();
  const popup = element.querySelector<HTMLElement>('[data-overflow-popup]')!;
  expect(popup.hidden).toBe(false);
  expect([...popup.querySelectorAll('button')].map(button => button.textContent)).toEqual(['Two', 'Three']);
  expect([...popup.querySelectorAll('button')].every(button => button.disabled)).toBe(true);
  expect(more.getAttribute('aria-expanded')).toBe('true');
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }));
  expect(popup.hidden).toBe(true);
  expect(document.activeElement).toBe(more);
  width = 50; observers.forEach(cb => cb()); flush();
  expect(buttons.every(button => button.inert)).toBe(true);
  expect(more.inert).toBe(false);
  width = 300; observers.forEach(cb => cb()); flush();
  expect(buttons.every(button => !button.inert)).toBe(true);
  expect(more.inert).toBe(true);
});
it('expands only the bounded vertical rail and recomputes its visible prefix on resize', async () => {
  const element = await artifact('holon-inspector');
  element.setContext({ nodeAffordances: { singularRelationships: ['One', 'Two', 'Very long relationship'].map(label => ({ label })) } });
  const rail = element.querySelector<HTMLElement>('[data-holon-inspector-single-value-rail]')!;
  const viewport = rail.querySelector<HTMLElement>('[data-rail-viewport]')!;
  const buttons = [...rail.querySelectorAll<HTMLButtonElement>('button:disabled')];
  const more = rail.querySelector<HTMLButtonElement>('[data-rail-more]')!;
  let height = 90;
  Object.defineProperty(rail, 'clientHeight', { get: () => height });
  buttons.forEach(button => measure(button, 100, 30)); measure(more, 100, 20);
  viewport.firstElementChild!.setAttribute('style', 'display:flex;flex-direction:column;row-gap:5px');
  rail.style.rowGap = '5px';
  document.body.append(element); flush();
  expect(buttons.map(button => button.style.visibility)).toEqual(['visible', 'visible', 'hidden']);
  more.click();
  expect(viewport.style.overflowY).toBe('auto');
  expect(rail.style.overflow).toBe('hidden');
  expect(buttons.every(button => !button.inert)).toBe(true);
  expect(buttons[2].style.overflowWrap).toBe('anywhere');
  more.click();
  expect(viewport.style.overflowY).toBe('hidden');
  height = 150; observers.forEach(cb => cb()); flush();
  expect(buttons.every(button => !button.inert)).toBe(true);
  expect(more.inert).toBe(true);
});

it('activates overflow relationship tabs and preserves keyboard access after selection', async () => {
  const node = await artifact('holon-inspector');
  const activate = vi.fn(); const dispose = vi.fn();
  const tabs = ['One', 'Two', 'Three'].map(label => ({ kind: 'relationship', label, relationship: { direction: 'declared' } }));
  node.setContext({ collectionActivation: { activate, dispose }, nodeAffordances: { collections: tabs } });
  const row = node.querySelector<HTMLElement>('[data-overflow-row]')!;
  let width = 200;
  Object.defineProperty(row, 'clientWidth', { get: () => width }); row.style.gap = '10px';
  const controls = [...row.querySelectorAll<HTMLButtonElement>('[role=tab]')];
  const more = row.querySelector<HTMLButtonElement>('[data-overflow-more]')!;
  controls.forEach(control => measure(control, 80)); measure(more, 100);
  document.body.append(node); flush();
  more.click();
  const popup = node.querySelector<HTMLElement>('[data-overflow-popup]')!;
  const entry = popup.querySelector<HTMLButtonElement>('button')!;
  expect(entry.disabled).toBe(false); expect(entry.tabIndex).toBe(0);
  entry.click();
  expect(activate).toHaveBeenCalledWith(tabs[1], 'HolonInspector.CollectionsSlot', expect.any(Function));
  expect(popup.hidden).toBe(true); expect(document.activeElement).toBe(more);
  expect(controls[1].getAttribute('aria-selected')).toBe('true');
  expect(controls.map(control => control.tabIndex)).toEqual([0, -1, -1]);
  expect(more.textContent).toBe('Two ▾');
  expect(more.dataset.overflowSelected).toBe('true');
  controls[0].click();
  expect(more.textContent).toBe('More collections');
  expect(more.dataset.overflowSelected).toBe('false');
  controls[1].click();
  width = 300; observers.forEach(cb => cb()); flush();
  expect(more.inert).toBe(true);
  expect(controls.map(control => control.tabIndex)).toEqual([-1, 0, -1]);
  expect(more.textContent).toBe('More collections');
  width = 200; observers.forEach(cb => cb()); flush();
  expect(controls.map(control => control.tabIndex)).toEqual([0, -1, -1]);
  expect(more.textContent).toBe('Two ▾');
  expect(more.dataset.overflowSelected).toBe('true');
  node.remove(); expect(dispose).toHaveBeenCalledOnce();
});


it('activates singular entries exposed by rail disclosure and reflects occurrence feedback', async () => {
  const element = await artifact('holon-inspector');
  const activate = vi.fn();
  const entries = ['First', 'Second', 'Third'].map(label => ({ label, relationship: { direction: 'declared' } }));
  element.setContext({ activateRelationship: activate, nodeAffordances: { singularRelationships: entries } });
  const rail = element.querySelector<HTMLElement>('[data-holon-inspector-single-value-rail]')!;
  const controls = [...rail.querySelectorAll<HTMLButtonElement>('[data-singular-relationship]')];
  const more = rail.querySelector<HTMLButtonElement>('[data-rail-more]')!;
  Object.defineProperty(rail, 'clientHeight', { get: () => 75 });
  controls.forEach(control => measure(control, 100, 30)); measure(more, 100, 20);
  document.body.append(element); flush();
  expect(controls[2].inert).toBe(true);
  more.click();
  expect(controls[2].inert).toBe(false);
  controls[2].focus(); controls[2].click();
  expect(activate).toHaveBeenCalledWith(entries[2]);
  expect(document.activeElement).toBe(controls[2]);
  (element as any).setSingularNavigationState({ state: 'loading', active: entries[0], attempted: entries[2] });
  expect(controls[0].getAttribute('aria-pressed')).toBe('true');
  expect(controls[2].getAttribute('aria-busy')).toBe('true');
  (element as any).setSingularNavigationState({ state: 'loaded', active: entries[2], attempted: entries[2] });
  expect(controls[0].getAttribute('aria-pressed')).toBe('false');
  expect(controls[2].getAttribute('aria-pressed')).toBe('true');
  expect(controls[2].getAttribute('aria-busy')).toBe('false');
});
