import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { expect, it, vi } from 'vitest';

it('retains the summary and collections through Path Inspector compression and restoration', async () => {
  const source = await readFile(resolve(process.cwd(), 'conductora/resources/dahn-visualizers/load-holons-inspector.js'), 'utf8');
  const { default: Node } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
  customElements.define('test-load-result-node', class extends Node {});
  const node = document.createElement('test-load-result-node') as any;
  const properties = document.createElement('section'), collections = document.createElement('section');
  collections.dataset.selectedRow = 'retained';
  node.setContext({ title: 'Load Holons', childVisualizers: new Map([['properties', properties], ['collections', collections]]) });
  document.body.append(node);
  const inspect = vi.fn();
  expect(node.setVisualizerInformationHandler).toBeTypeOf('function');
  node.setVisualizerInformationHandler(inspect, 'Load Holons Inspector');
  const information = node.querySelector('[data-visualizer-information]') as HTMLButtonElement;
  expect(information.hidden).toBe(false);
  expect(information.getAttribute('aria-label')).toBe('Visualizer information: Load Holons Inspector');
  information.click(); expect(inspect).toHaveBeenCalledWith(information);
  node.setVisualizerInformationHandler(undefined, 'Load Holons Inspector');
  expect(information.hidden).toBe(true);
  const restore = vi.fn(); node.setOccurrenceRestorationHandler(restore);
  const extents = node.getNodeInspectorExtents();
  expect(extents.vertical['full-height']).toBeGreaterThan(extents.vertical['partial-height']);
  node.setNodeInspectorAllocation({ width: 120, height: 48, vertical: 'minimal-height', horizontal: 'minimal-width' });
  expect(properties.parentElement!.hidden).toBe(true);
  node.querySelector('header button').click(); expect(restore).toHaveBeenCalledOnce();
  node.setNodeInspectorAllocation({ width: 900, height: 760, vertical: 'full-height', horizontal: 'full-width' });
  expect(properties.parentElement!.hidden).toBe(false);
  expect(collections.isConnected).toBe(true); expect(collections.dataset.selectedRow).toBe('retained');
  node.remove();
});
