[package]
name = "descriptors"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "descriptors"

[dependencies]
# General Dependencies
derive-new = { workspace = true }
Inflector = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Holochain Dependencies
hdk = { workspace = true }
hdi = { workspace = true }

# MAP Dependencies
holons = { workspace = true }
shared_types_holon = { workspace = true }


# General dev-dependencies (platform-agnostic)
[dev-dependencies]


# Target-specific dev dependencies for non-WASM builds
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
holochain = { version = "0.3", default-features = false, features = ["test_utils", "sqlite-encrypted"] }
tokio = { version = "1.35.1", features = ["full"] }