[package]
name = "dances"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "dances"

[dependencies]

# General Dependencies
serde = { workspace = true }
derive-new = { workspace = true }

# Holochain Dependencies
hdk = { workspace = true }
hdi = { workspace = true }


# MAP Dependencies
shared_types_holon = { workspace = true }
holons = { workspace = true }
holons_core = { workspace = true }
core_schema = { workspace = true }
holons_init = { workspace = true }
holons_guest = { workspace = true }


# General dev-dependencies (platform-agnostic)
[dev-dependencies]
async-std = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }

# Target-specific dev dependencies for non-WASM builds
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
holochain = { version = "0.3", default-features = false, features = ["test_utils", "sqlite-encrypted"] }
tokio = { version = "1.35.1", features = ["full"] }