[package]
name = "base_types"
version = "0.1.0"
edition = "2021"


[dependencies]
convert_case = { workspace = true }
derive-new = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }